Repository MicrosoftDocs/xamarin-docs.es-es, pull requests merged in 2019-02, with the labels that each got.

#39 Update passkit.md
  docs/ios/platform/passkit.md
Labels: Accepted with changes, Linguistic Suggestion

#44 Mala redacción
  docs/get-started/index.md
Labels: Accepted, Linguistic Suggestion

#43 Mala estructura en la redacción
  docs/get-started/index.md
Labels: Accepted with changes, Linguistic Suggestion

#45 Error
  docs/xamarin-forms/app-fundamentals/index.md
Labels: Accepted with changes, Linguistic Suggestion

#47 Falta una letra
  docs/xamarin-forms/app-fundamentals/index.md
Labels: Accepted, Linguistic Suggestion

#49 Corrección de redacción
  docs/android/platform/index.md
Labels: Accepted, Linguistic Suggestion

#50 Error en la traduccion y redaccion
  docs/cross-platform/desktop/index.md
Labels: Accepted, Linguistic Suggestion

#53 correcciones
  docs/xamarin-forms/data-cloud/search/azure-search.md
Labels: Accepted, Linguistic Suggestion

#52 Redacción
  docs/xamarin-forms/internals/net-standard.md
Labels: Linguistic Suggestion, Partially Accepted

#40 Corrección de redacción
  docs/get-started/index.md
Labels: Linguistic Suggestion, Partially Accepted

#42 Bad translation
  docs/cross-platform/platform/index.md
Labels: Linguistic Suggestion, Partially Accepted

#51 Corrección de redacción
  docs/xamarin-forms/xaml/index.md
Labels: Linguistic Suggestion, Partially Accepted

#55 Correcion de redaccion
  docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md
Labels: Linguistic Suggestion, Partially Accepted

#68 Corrección de palabra
  docs/xamarin-forms/user-interface/graphics/skiasharp/index.md
Labels: Accepted, Linguistic Suggestion

#67 corrección para una mejor comprensión del texto.
  docs/android/app-fundamentals/accessibility.md
Labels: Accepted, Linguistic Suggestion

#65 Redacción
  docs/xamarin-forms/enterprise-application-patterns/index.md
Labels: Accepted, Linguistic Suggestion

#62 Palabra mal
  docs/xamarin-forms/enterprise-application-patterns/index.md
Labels: Linguistic Suggestion, Partially Accepted

#61 Eliminación de Palabra Repetida y cambio
  docs/xamarin-forms/user-interface/graphics/skiasharp/index.md
Labels: Accepted, Linguistic Suggestion

#70 cambio en la redacción
  docs/xamarin-forms/internals/dependency-resolution.md
Labels: Linguistic Suggestion, Partially Accepted
